# 연령층 분포
AGE_POPULATION_KEY = "AGE_POPULATION"
MOVE_PEOPLE_KEY = "MOVE_PEOPLE"
PLANNING_MOVE_KEY = "PLANNING_MOVE_KEY"
HOUSING_FAQ_KEY = "HOUSING_FAQ"
HOUSING_RULE_KEY = "HOUSING_RULE"
UNSOLD_HOUSING_KEY = "UNSOLD_HOUSING"
NATIONAL_POLICY_KEY = "NATIONAL_POLICY"
